### ISSUE TITLE
No safe way to get individual elements from `Mat`

### ISSUE THREAD

**Issue by joshhansen** [nebgnahz/cv-rs#20]
Whereas the `cv::Mat` class in OpenCV provides a series of `at` methods that (if I understand correctly) return individual elements of the array, cv-rs's `Mat` provides no such methods. It seems the only way to access the actual content of the matrix is by using `data(&self)` which returns a u8 pointer to the backing data, and requires the user to understand the layout of the data, and to perform unsafe operations simply to get matrix elements. As accessing matrix elements is likely to be a common operation, it seems it would be appropriate to add equivalents to the `at` methods to cv-rs's `Mat` implementation.

**Comment by nebgnahz** [comment]
You are right that the only way to access backing data within a `Mat` is to use `data(&self)`. Implementing `at` will add convenience.

With that said, I do have some concerns. OpenCV's [`at`](https://github.com/opencv/opencv/blob/2808bea7faf902e8872613cb971703dcdca4217b/modules/core/include/opencv2/core/mat.hpp#L1851) is actually complicated because of template and function overload:

```c++
    template<typename _Tp> _Tp& at(int i0=0);
    template<typename _Tp> const _Tp& at(int i0=0) const;
    template<typename _Tp> _Tp& at(int row, int col);
    template<typename _Tp> const _Tp& at(int row, int col) const;
    template<typename _Tp> _Tp& at(int i0, int i1, int i2);
    template<typename _Tp> const _Tp& at(int i0, int i1, int i2) const;
    template<typename _Tp> _Tp& at(const int* idx);
    template<typename _Tp> const _Tp& at(const int* idx) const;
    template<typename _Tp, int n> _Tp& at(const Vec<int, n>& idx);
    template<typename _Tp, int n> const _Tp& at(const Vec<int, n>& idx) const;
    template<typename _Tp> _Tp& at(Point pt);
    template<typename _Tp> const _Tp& at(Point pt) const;
```

If we are adding this API to `cv-rs`, we need to address three issues:
- [ ] What's the API of `at` in Rust binding? For example, with row and column, do we use `at(isize, isize)`, `at((isize, isize))` or `at2(isize, isize)`?
- [ ] To call C++ `at`, we need to provide the right template argument that depends on the `Mat` type, `CV_64F`, `CV_32F`, `CV_8U` will be `double`, `float`, and `uchar`, respectively.
- [ ] What's the return type? C++ returns a reference with type `_Tp`; and that need to converted to Rust types.

We don't have to solve all of them perfectly; we can probably start with the ones that's mostly common. For my applications, they don't need to access individual elements of `Mat`, which is why I haven't implemented this. What's your application's demand? Maybe we can start from there.

**Comment by joshhansen** [comment]
My application is very unusual and ad hoc. I have data trapped in a laptop whose network, usb, audio, etc. are broken. I'm attempting to use the computer's screen to transmit the data out by flashing the screen white or black to signal bits. I'm using your library to write a rust application to run on another computer and decode the transmitted bits using a webcam. I need to be able to determine the color of individual parts of the incoming image in order to interpret the video stream appropriately.

You're right that there are some challenges since the `at` functionality is templated. Perhaps Rust's traits can provide an answer to that? If we define a trait such as `FromBytes` for types that can be read directly from the backing data, then we can probably implement `at` generically (as far as datatype):

    pub fn <T:FromBytes> at1(&self, i0: isize) -> T {
        let data: *const u8 = self.data();
        unsafe {
            let el_ptr: *const u8 = data.offset( i0 * self.elem_size() as isize );
            T::from_bytes(el_ptr)
        }
    }

    pub fn <T:FromBytes> at2(i0: isize, i1: isize) -> T { ... }

etc.

In this approach, we wouldn't actually call the C++ `at` but instead we re-implement its functionality. This sidesteps some of the templating issues, but leaves us maintaining our own versions of these existing functions.

We could do something like that for now, and then whenever  [const generics](https://github.com/rust-lang/rfcs/blob/master/text/2000-const-generics.md) are implemented we could introduce a more generic version of `at`:

    pub fn <T:FromBytes, const N: usize> at(indices: [isize; N]) -> T { ... }

At least, I think that should be possible. In fact, it seems that some of the `at` overloads are themselves using "const generics" (not sure what it's called in C++) in a similar way:

    template<typename _Tp , int n> 
    _Tp& cv::Mat::at(const Vec<int, n> & idx) { ... }

Another approach, which would use the existing `at` methods from C++ instead of implementing them entirely in Rust, might look something like this:

    trait At {
        fn at1(mat: &Mat, i0: isize) -> Self;
        fn at2(mat: &Mat, i0: isize, i1: isize) -> Self;
        ...
    }
    impl At for f32 {
        fn at1(mat: &Mat, i0: isize) -> Self {
            let mat_ptr = mat as *const Mat;
            unsafe { cv_mat_at_float(mat_ptr, i0) }
        }
        fn at2(mat: &Mat, i0: isize, i1: isize) -> Self { ... }
        ...
    }
    ...

Then on `Mat`:

    pub <T:At> fn at1(&self, i0: isize) -> T {
        T::at1(self, i0)
    }
    pub <T:At> fn at2(&self, i0: isize, i1: isize) -> T {
        T::at2(self, i0, i1)
    }
    ...

Something like that?

**Comment by nebgnahz** [comment]
I took the `FromBytes` approach and now have a branch/PR #21. Please take a look and let me know what you think!

**Comment by joshhansen** [comment]
Very nice! Thanks for the quick work on this! And good call getting rid of the `At` trait---I had a feeling it might be disposable.

I've written a little program to test out the new functionality:

```rust
use std::fs::File;
use std::io::Read;

use cv::Mat;
use cv::imgcodecs::ImreadModes;

pub fn test_at() {
    let mut file = File::open("test/red_10x10.png").unwrap();
    let mut bytes: Vec<u8> = Vec::new();
    let len = file.read_to_end(&mut bytes).unwrap();
    let mat = Mat::imdecode(&bytes, ImreadModes::ImreadColor);

    let size = mat.size();
    for x in 0..size.width {
        for y in 0..size.height {
            let rgb: (u8,u8,u8) = mat.at2(0, 0);
            println!("{},{} -> {:?}", x, y, rgb);
        }
    }
}
```

The input image is a 10x10 image of pure red. The output of the program is a bunch of lines with "(0, 0, 255)", so it seems that when reading RGB triples the order of RGB is reversed. Testing with green and blue files confirms this: green gives "(0, 255, 0)" and blue gives "(255, 0, 0)".

My application is a fun little challenge born of a hard drive failure :-) I actually am enjoying it well, and it gives me an excuse to work on my Rust.

**Comment by joshhansen** [comment]
I also had one question: right now the `at` functions are taking `isize` arguments. Does it make sense for this to be signed? Would the coordinates ever be negative?

**Comment by joshhansen** [comment]
Here are some test images for use with the above test program. I'm getting an error reading black_blue_20x10.png, which comes out as all zeroes:

![blue_10x10](https://user-images.githubusercontent.com/733906/33109767-b4f78560-cf00-11e7-96a3-b8cec0019946.png)
![green_10x10](https://user-images.githubusercontent.com/733906/33109768-b51074c6-cf00-11e7-8d7a-24d1abb344b4.png)
![red_10x10](https://user-images.githubusercontent.com/733906/33109769-b52af6fc-cf00-11e7-9874-32072efdfc13.png)
![black_blue_20x10](https://user-images.githubusercontent.com/733906/33109679-3d3bcc20-cf00-11e7-95ac-7cdc85054358.png)
![blue_black_20x10](https://user-images.githubusercontent.com/733906/33109680-3d6bfcce-cf00-11e7-9a62-56da7efba713.png)

**Comment by nebgnahz** [comment]
Replying to your first RGB question: 

When use `ImreadColor`, OpenCV always converts image to the 3 channel BGR color image.
See [OpenCV documentation](https://docs.opencv.org/3.3.0/d4/da8/group__imgcodecs.html#gga61d9b0126a3e57d9277ac48327799c80af660544735200cbe942eea09232eb822) and [cv-rs documentation](https://nebgnahz.github.io/cv-rs/cv/imgcodecs/enum.ImreadModes.html#variant.ImreadColor).

---

About `isize` vs `usize`, I prefer `usize` but implement it using `isize` as it is more coherent with OpenCV's `int` type (actually `i32` might be closer). `Mat::size` returns `Size2i` which is `i32`, but we know the size should be unsigned... I am thinking about using `i32` consistently.

About negative coordinates, since internally OpenCV (and this PR) calculates the position with simple algebra, perhaps one can  to perform some _creative_ tricks to access the previous row. I am lacking imagination here, though.

---

I will test your png images tomorrow and see what goes wrong.

**Comment by nebgnahz** [comment]
I am merging the PR and closing this one. If you still have issues, feel free to re-open or create new ones.

**Comment by joshhansen** [comment]
Sounds good---thanks for answering my previous questions. I'm new to OpenCV and so was confused, but it looks like everything is working properly.
