### ISSUE TITLE
Feature Request: Template Matching

### ISSUE THREAD

**Issue by onelson** [nebgnahz/cv-rs#64]
Hi again,
Here I am with yet another feature request!

**Comment by Pzixel** [comment]
Can you be more concrete? There is some matching: https://nebgnahz.github.io/cv-rs/cv/features2d/index.html

**Comment by Pzixel** [comment]
Ok, I see.

I think I can handle it, but i'd like to perform some refactoring first. If @nebgnahz is not against, I think we need split `opencv-wrapper` file into small pieces, because it's already hard to maintain, it's almost 1k sloc in there, as well as `core.rs` file. I showed an approach that allows to write code with less effort (text and features2d modules). If he is ok with it, I'l take this issue after refactoring is done.

**Comment by Pzixel** [comment]
Well, I have a bizzare idea to remove `C` part at all and bindgen some stuff. I already successfully generated bindings for `core`, and I'm going to continue. It may greatly increase stuff we can wrap on as well as reduce time for future feature introduction.

**Comment by Pzixel** [comment]
@estw272 sorry, this task revealed to be much more complicated then I could expect. I didn't get enough time to decompose python bindings generator and rewrite it in Rust. It seems that `opencv` crate approach is much better. I think we should take it and adopt for OpenCV 3.X. Manually adopting some parts of opencv is a noway, unfortuantely. See #67

**Comment by onelson** [comment]
Just wanted to caution against following the generation approach being used by the `opencv` crate too closely. My limited experience with the crate was fraught with segfaults while manipulating Mat data. Something was not right with the memory access over there.

**Comment by Pzixel** [comment]
@onelson I think it's due to bad implementation itself, but this approach is the only doable. Otherwise it's "5% of features and toy example" as result.

**Comment by nebgnahz** [comment]
I have also made attempts generating bindings automatically (either `bindgen` or `gen.py`-adapted). Those were not successful and quite time consuming.

At this point, I think this project works; despite the coverage of all OpenCV functionality is small, I can use this in my other projects. So I plan to continue porting functions and modules until someone (maybe @Pzixel or others) has a better way.

**Comment by Pzixel** [comment]
@onelson sorry I didn't been here for a while, I was a bit disappointed in the project, becuase it doesn't seems feasible to handle it by my own. Unfortunately, @nebgnahz have no time to work here, and I didn't see how to advance. However, now I think that something working in Rust is better than nothing. Instead of writing your own wrappers you can add them here. So it's a bit less painful, we have been workarounded some pitfalls and may share it with people.

I hope you can forgive me if I let you down and you had some plans on soon implementation.

**Comment by onelson** [comment]
Not to worry! Seems like the challenges you have faced here will be similar to all other rust/opencv implementations. I think if there's going to be a viable workflow it'll take some changing from the opencv side.

Thanks for your hard work so far! I'll figure something out and report back if there's anything worth sharing here.
