### ISSUE TITLE
Publish into crates.io

### ISSUE THREAD

**Issue by Pzixel** [nebgnahz/cv-rs#78]
We need to publish this crate into `crates.io`

It the must do thing that wasn't yet accomplished.

What do you think? It still be a toy project that shouldn't appear in places like `crates`? 

Do you have some plans to enhance the library? We did a great job, the library has a single code standard, good readme, nice code conduct and so on... But is it alive?

I understand that you have your own life, but if you don't commit at least once a month then it's probably better to not give people a hope that there is something like that. I neither have an answer what's the right way, It's just a question that appeared suddenly in my head.

**Comment by nebgnahz** [comment]
Hey, @Pzixel, apologies first for the slow response. The busiest time for me has passed, and I can return back to work :) And thanks for handling the PR/issues.

I have thought about publishing on `crates.io`. But hesitated to do so given lack of coverage in terms of functionality.

Also the current process of manually implementing wrappers doesn't feel right to me (it is a good starting point for toy projects though).

I have also re-evaluated the options of automatically generating bindings and failed again. Do you have any luck?

While I was doing some digging into bindgen, I noticed [gocv](https://github.com/hybridgroup/gocv/), which has already implemented all the C wrappers needed for Go to use. So I experimented a bit with bindgen Rust APIs from there. You can find the work in progress here: [code](https://github.com/nebgnahz/rustcv) and [doc](https://nebgnahz.github.io/rustcv/rustcv/).

The generated bindings documented as `opencv_sys` crate is available (https://nebgnahz.github.io/rustcv/opencv_sys/index.html) and accessible as `ffi` module. As a result, adding new functionality is a pure Rust task (so folks who are not familiar with C/C++ don't need to worry about it):

e.g. [median_blur](https://github.com/nebgnahz/rustcv/blob/master/src/imgproc.rs#L281):

```rust
/// Blurs an image using the median filter.
pub fn median_blur(src: &Mat, dst: &mut Mat, size: i32) {
    unsafe { ffi::MedianBlur(src.inner, dst.inner, size) }
}
```

The hope is that there will be one place that all developers can contribute to for the C wrapper (i.e. `gocv`) and both Rust/Go will generate bindings from there.

Since this approach is not compatible with `cv-rs`, I made it a separate repo for now. If it is a viable approach, we can either merge the implementation here or provide a redirect message from this repo there.

What do you think?

**Comment by Pzixel** [comment]
What if we just reuse these python scripts without rewriting them into something else? I believe that we can ask developers to just install python and end with it. If we use "bindgen CLI" for this we wouldn't face the big problems cause we will have all headers pregenerated into repository, just like "Cargo.lock".

**Comment by nebgnahz** [comment]
I spent some time looking into the python generated and didn't figure out a nice way of directly using it. To interface Python, the generated code has the following signature 

```
// template: static PyObject* pyopencv_cv_xxxx(PyObject* , PyObject* args, PyObject* kw)
static PyObject* pyopencv_cv_AKAZE_create(PyObject* , PyObject* args, PyObject* kw);
static PyObject* pyopencv_cv_PSNR(PyObject* , PyObject* args, PyObject* kw);
// ...
```

And within the function body, `args` are parsed with `PyArg_ParseTupleAndKeywords`. berak also mentioned:

> i tried to eat my own dog-food recently, trying to automate opencv wrappers for gocv, but after putting in like 60 hrs on some (current 1038 lines) python script, based on gen2.py, results are only 70%correct. this IS terribly hard !

So at this point, I am uncertain if another 60 hrs (or even more) would be helpful. 

I do think join force with gocv is a good step forward, e.g. this issue: https://github.com/hybridgroup/gocv/issues/100.

----

Re: NEVER EVER USE BINDGEN CRATE. USE CLI ONLY AND COMMIT GENERATED CODE INTO REPO OR YOUR LIFE BECOMES A NIGHTMARE.

I have been using `bindgen` for a few other projects recently and see the issues with using `bindgen` crate; but as the source/wrapper code evolves and `bindgen` evolves, commenting and committing the generated code does not seem to be viable to me. Can you elaborate here?

**Comment by Pzixel** [comment]
> I do think join force with gocv is a good step forward

I do believe it's a step forward indeed. But I also think we may try to have a bigger leap forward. Maybe it's too unrealistic and optimistic, I'd just like to know your opinion on this matter. Maybe spending another 60hrs doesn't worth it, but maybe it is. For what it worth having a opencv-sys crate to be completely autogenerated is a huge win in all senses. Of course we would require to wrap it in rust traits and so on then, but it would be so much simpler. Having it on top of the native opencv script would be a guaranty of the most compatible and complete shim. 

> I have been using bindgen for a few other projects recently and see the issues with using bindgen crate; but as the source/wrapper code evolves and bindgen evolves, commenting and committing the generated code does not seem to be viable to me. Can you elaborate here?

I only can retranslate the words I heard from the people that worked on it and that I have already written above. If you want some more concrete examples of what could go wrong I could ask them.

**Comment by nebgnahz** [comment]
I am with you about trying it out; but my Python-ability is limited. If you have something, I am happy to help, though. Also when I say "join force with gocv", I mean joining force on generating opencv-sys as well. I am sure it will benefit `gocv` as well.

**Comment by Pzixel** [comment]
I think we may even transform python wrapper itself into rust wrapper, it probably could be more efficient way to achieve the goal, don't you think?

I want to try to run this script first and see what it generates because I didn't do it even once.

**Comment by Pzixel** [comment]
I've asked some help from the opencv team itself, let's see what's their positions is.

I wrote some of my considerations here: https://github.com/opencv/opencv/issues/11666

**Comment by Pzixel** [comment]
Close for now
